#!/bin/bash
set -x
set -e

newver=$1
headof=$2

if [[ -z "$1" ]]; then
  echo "Usage: $0 newver [headof]"
  exit 1
fi

export RBENV_ROOT=/usr/share/rbenv

export RUBY_CONFIGURE_OPTS="--enable-shared --enable-pthread --disable-install-doc --disable-install-capi"
export optflags="-O2"

###

if [ -z $headof ]; then
  headof=${newver:0:3}
fi

##

export PATH=/usr/lib/distcc/bin:/usr/local/bin:/usr/bin:/bin:/opt/bin:/usr/x86_64-pc-linux-gnu/gcc-bin/4.6.3
export PATH=$RBENV_ROOT/shims:$RBENV_ROOT/bin:$PATH

unset GEM_PATH
unset BUNDLE_BIN_PATH
unset BUNDLE_GEMFILE
unset RUBYOPT
unset RUBYLIB

rbenv install $newver
rbenv global $newver
export RBENV_VERSION=$newver

gem i bundler --no-rdoc --no-ri
gem i foreman --no-rdoc --no-ri
rbenv global-rehash /usr/bin

if [[ ( ! -z $headof ) ]]; then
  ln -sfT $newver $RBENV_ROOT/versions/$headof
fi
